### ISSUE TITLE
Incorrectly charged for usage

### ISSUE THREAD

**Issue by bradyjoslin** [fancyhands/api#18]
Hi - I have been doing some experiments with the API.  The "Use Real Requests" switch has been set to off during these tests, but I was charged for some of the Custom API requests that I've submitted.  Looks like I was immediately charged the bid price.  No work was performed.

Also, when I login to my personal FH account, I see all of those request there showing as "in process".

**Comment by steveodom** [comment]
Same issue here. It looks like I need those credits to test the API.
