### ISSUE TITLE
simulating webhook post

### ISSUE THREAD

**Issue by steveodom** [fancyhands/api#20]
I'd like to test incoming posts to my designated webhook. How do we do that? I was hoping sample requests made through the API explorer would send updates to the webhook, but it doesn't appear to.  

I suppose requests made through the API will update here, but I'm not currently able to submit test requests (see: https://github.com/fancyhands/api/issues/18)

**Comment by tedroden** [comment]
We have an endpoint for this:

https://www.fancyhands.com/api/explorer#/explorer/fancyhands.request.Callback

After you create a request, you can just ping that with the request key and it'll ping your webhook callback url.
