### ISSUE TITLE
Cant add money to my account

### ISSUE THREAD

**Issue by pekbac** [fancyhands/api#21]
Hi,

I was looking into testing your API. I understood I need to add API Credit, and your site took me here:

https://www.fancyhands.com/billinginfo/api/#billing-page

I entered all my card details and clicked the green button and it took me to a page that says:

     405 Method Not Allowed
     The method POST is not allowed for this resource. 

Is something broken, or is this an outdated link I followed? How do I get started here?

**Comment by tedroden** [comment]
Yikes! My bad. That should be fixed now. Just refresh and get going.

Also, if you're just testing the API for the first time, your account is loaded with $30 in free credits.
