### ISSUE TITLE
Attachments/documents

### ISSUE THREAD

**Issue by owensbla** [fancyhands/api#23]
I recently scheduled a task in which the assistant attached a document with some research. I didn't see any references to documents or attachments on any of the endpoints, is there an undocumented field where I can fetch URLs for attachments?

**Comment by tedroden** [comment]
Hrm. Good question. It may show up in the list of `messages` when you `GET` it, but I doubt it will be in any usable format. 

I'll dig around and see if I can add that in a better format.

**Comment by tedroden** [comment]
OK, attachments are in the response in a usable format.

They should show up in any request where an attachment is possible:

```json
  {
    "attachments": [
	{
            "user": {
		"first_name": "John",
		"assistant_avatar_id": 0,
		"key": "alksdjf-asdfasdf-asdflkjlk-laks",
		"display_name": "John D."
            },
            "url": "https://www.fancyhands.com/request/attachment/li2j3lijalsdkjp932jlkasdjlijlicje32kjclkj",
            "date_created": "2019-04-06T19:50:15.153036",
            "content_type": "image/png",
            "filename": "Screen Shot 2019-02-04 at 5.06.33 PM.png",
            "filesize": 162712,
            "attachment_key": "li2j3lijalsdkjp932jlkasdjlijlicje32kjclkj",
            "image_thumb": null
	}
    ]
}
```

**Comment by owensbla** [comment]
Awesome, thanks @tedroden.
